const mongoose = require('mongoose');

const notificationSchema = new mongoose.Schema({
  recipient: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true 
  },
  sender: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    default: null // Can be null if generated by the system (e.g. Website Form)
  },
  type: { 
    type: String, 
    enum: ['New Message', 'New Brief', 'New Lead', 'New Project', 'New Task', 'Task Update', 'Mention'],
    required: true
  },
  title: { type: String, required: true },
  message: { type: String, required: true },
  link: { type: String, required: false }, // URL or path to navigate to when clicked
  isRead: { type: Boolean, default: false },
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Notification', notificationSchema);
